const fs = require('fs');
const path = require('path');

const target = path.join(process.cwd(), 'src', 'app', 'investor', 'portal', 'page.tsx');
let code = fs.readFileSync(target, 'utf8');

const cardsBlock = [
  '              <div className=" space-y-3\>',
 ' {customers.map((c) => {',
 ' const progress = c.sellingPrice > 0 ? Math.round((c.totalPaid / c.sellingPrice) * 100) : 0;',
 ' return (',
 ' <div key={c.id} className=\p-4 rounded-xl border border-border/50 hover:border-primary/40 bg-card/60 transition-all space-y-3\>',
 ' {/* Top Header: Customer Info, Phone, ID & Badge */}',
 ' <div className=\flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-border/30\>',
 ' <div className=\flex items-center gap-3\>',
 ' {c.image ? (',
 ' <img src={c.image} alt={c.name} className=\w-10 h-10 rounded-full object-cover border border-primary/30\ />',
 ' ) : (',
 ' <div className=\w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold text-sm\>',
 ' {c.name.charAt(0).toUpperCase()}',
 ' </div>',
 ' )}',
 ' <div>',
 ' <div className=\flex items-center gap-2\>',
 ' <p className=\font-semibold text-sm text-foreground\>{c.name}</p>',
 ' {c.idNumber && (',
 ' <Badge variant=\secondary\ className=\text-[10px] font-mono px-1.5 py-0\>',
 ' #{c.idNumber}',
 ' </Badge>',
 ' )}',
 ' </div>',
 ' <p className=\text-xs text-muted-foreground flex items-center gap-1 mt-0.5\>',
 ' <Phone className=\w-3 h-3 text-muted-foreground\ /> {c.phone1} {c.phone2 ? • : \\}',
 ' </p>',
 ' </div>',
 ' </div>',
 ' <div className=\flex items-center gap-2 self-start sm:self-auto\>',
 ' <Badge',
 ' variant={c.status === \completed\ ? \success\ : c.status === \defaulted\ ? \destructive\ : \outline\}',
 ' className=\text-[10px]\',
 ' >',
 ' {c.status === \completed\ ? \Completed ✓\ : c.status === \defaulted\ ? \Defaulted ✕\ : ${c.paidInstallments}/ months}',
 ' </Badge>',
 ' <Button',
 ' size=\sm\',
 ' variant=\outline\',
 ' className=\h-7 px-2.5 text-xs gap-1 border-primary/30 hover:bg-primary/10 text-primary\',
 ' onClick={() => setSelectedCustomerDetail(c)}',
 ' >',
 ' <Eye className=\w-3.5 h-3.5\ /> Full Details',
 ' </Button>',
 ' </div>',
 ' </div>',
 '',
 ' {/* Details Strip: Mobile, IMEIs, Referred By, Dates */}',
 ' <div className=\grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 text-xs bg-muted/20 p-2.5 rounded-lg border border-border/30\>',
 ' <div className=\flex items-center gap-1.5\>',
 ' <Smartphone className=\w-3.5 h-3.5 text-primary shrink-0\ />',
 ' <span className=\font-medium text-foreground\>{c.mobileCompany} {c.mobileModel}</span>',
 ' </div>',
 ' <div className=\flex items-center gap-1.5\>',
 ' <Fingerprint className=\w-3.5 h-3.5 text-muted-foreground shrink-0\ />',
 ' <span className=\text-muted-foreground font-mono\>IMEI 1: <strong className=\text-foreground\>{c.imei1 || \N/A\}</strong></span>',
 ' </div>',
 ' {c.imei2 && (',
 ' <div className=\flex items-center gap-1.5\>',
 ' <Fingerprint className=\w-3.5 h-3.5 text-muted-foreground shrink-0\ />',
 ' <span className=\text-muted-foreground font-mono\>IMEI 2: <strong className=\text-foreground\>{c.imei2}</strong></span>',
 ' </div>',
 ' )}',
 ' <div className=\flex items-center gap-1.5\>',
 ' <UserCheck className=\w-3.5 h-3.5 text-purple-400 shrink-0\ />',
 ' <span className=\text-muted-foreground\>Referred By: <strong className=\text-purple-300\>{c.resellerName || \Direct / Shop\}</strong></span>',
 ' </div>',
 ' <div className=\flex items-center gap-1.5\>',
 ' <Calendar className=\w-3.5 h-3.5 text-muted-foreground shrink-0\ />',
 ' <span className=\text-muted-foreground\>Sale Date: <strong className=\text-foreground\>{formatDate(c.createdAt)}</strong></span>',
 ' </div>',
 ' {c.nextDueDate && (',
 ' <div className=\flex items-center gap-1.5\>',
 ' <Clock className=\w-3.5 h-3.5 text-amber-400 shrink-0\ />',
 ' <span className=\text-muted-foreground\>Next Due: <strong className=\text-amber-400\>{formatDate(c.nextDueDate)}</strong></span>',
 ' </div>',
 ' )}',
 ' </div>',
 '',
 ' {/* Progress Bar & Financial Breakdown */}',
 ' <div className=\space-y-1.5\>',
 ' <div className=\flex justify-between text-xs\>',
 ' <span className=\text-muted-foreground\>Payment Progress:</span>',
 ' <span className=\font-medium text-foreground\>{progress}% ({formatCurrency(c.totalPaid)} / {formatCurrency(c.sellingPrice)})</span>',
 ' </div>',
 ' <Progress value={progress} className=\h-1.5\ />',
 ' <div className=\grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px] pt-1 text-muted-foreground\>',
 ' <div>Invested: <strong className=\text-blue-400\>{formatCurrency(c.investmentUsed)}</strong></div>',
 ' <div>Advance: <strong className=\text-emerald-400\>{formatCurrency(c.advancePayment)}</strong></div>',
 ' <div>Monthly: <strong className=\text-purple-400\>{formatCurrency(c.monthlyInstallment)}</strong></div>',
 ' <div>Remaining: <strong className=\text-amber-400\>{formatCurrency(c.remainingAmount)}</strong></div>',
 ' </div>',
 ' </div>',
 ' </div>',
 ' );',
 ' })}',
 ' </div>'
].join('\n');

const dialogBlock = [
 ' {/* Full Customer Detail View Dialog */}',
 ' <Dialog open={!!selectedCustomerDetail} onOpenChange={(open) => !open && setSelectedCustomerDetail(null)}>',
 ' <DialogContent className=\max-w-2xl max-h-[90vh] overflow-y-auto\>',
 ' {selectedCustomerDetail && (',
 ' <>',
 ' <DialogHeader>',
 ' <div className=\flex items-center justify-between gap-2 pr-6\>',
 ' <DialogTitle className=\flex items-center gap-2 text-xl\>',
 ' <User className=\w-5 h-5 text-primary\ />',
 ' {selectedCustomerDetail.name}',
 ' {selectedCustomerDetail.idNumber && (',
 ' <Badge variant=\secondary\ className=\font-mono text-xs\>',
 ' #{selectedCustomerDetail.idNumber}',
 ' </Badge>',
 ' )}',
 ' </DialogTitle>',
 ' <Badge',
 ' variant={selectedCustomerDetail.status === \completed\ ? \success\ : selectedCustomerDetail.status === \defaulted\ ? \destructive\ : \outline\}',
 ' className=\text-xs shrink-0\',
 ' >',
 ' {selectedCustomerDetail.status === \completed\ ? \Completed ✓\ : selectedCustomerDetail.status === \defaulted\ ? \Defaulted ✕\ : \Active Sale\}',
 ' </Badge>',
 ' </div>',
 ' <DialogDescription>',
 ' Full Customer & Mobile Details (Investor View)',
 ' </DialogDescription>',
 ' </DialogHeader>',
 '',
 ' <div className=\space-y-5 my-2\>',
 ' {/* Customer / Mobile Photo Preview */}',
 ' {selectedCustomerDetail.image && (',
 ' <div className=\flex justify-center p-3 bg-black/40 rounded-xl border\>',
 ' <img',
 ' src={selectedCustomerDetail.image}',
 ' alt=\Customer / Mobile\',
 ' className=\max-h-48 rounded-lg object-contain\',
 ' />',
 ' </div>',
 ' )}',
 '',
 ' {/* Grid 1: Customer Personal Details */}',
 ' <div className=\p-4 rounded-xl bg-muted/30 border space-y-3\>',
 ' <h4 className=\text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5\>',
 ' <User className=\w-3.5 h-3.5 text-primary\ /> Customer Personal Details',
 ' </h4>',
 ' <div className=\grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs\>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Full Name:</span>',
 ' <span className=\font-semibold text-sm\>{selectedCustomerDetail.name}</span>',
 ' </div>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Primary Phone:</span>',
 ' <span className=\font-semibold text-sm text-primary flex items-center gap-1\>',
 ' <Phone className=\w-3 h-3\ /> {selectedCustomerDetail.phone1}',
 ' </span>',
 ' </div>',
 ' {selectedCustomerDetail.phone2 && (',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Secondary Phone:</span>',
 ' <span className=\font-medium flex items-center gap-1\>',
 ' <Phone className=\w-3 h-3\ /> {selectedCustomerDetail.phone2}',
 ' </span>',
 ' </div>',
 ' )}',
 ' </div>',
 ' </div>',
 '',
 ' {/* Grid 2: Mobile Phone & IMEIs */}',
 ' <div className=\p-4 rounded-xl bg-purple-500/5 border border-purple-500/20 space-y-3\>',
 ' <h4 className=\text-xs font-semibold uppercase tracking-wider text-purple-400 flex items-center gap-1.5\>',
 ' <Smartphone className=\w-3.5 h-3.5\ /> Mobile Phone & IMEI Details',
 ' </h4>',
 ' <div className=\grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs\>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Company & Model:</span>',
 ' <span className=\font-bold text-sm text-foreground\>{selectedCustomerDetail.mobileCompany} {selectedCustomerDetail.mobileModel}</span>',
 ' </div>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>IMEI 1:</span>',
 ' <span className=\font-mono font-bold text-sm text-emerald-400\>{selectedCustomerDetail.imei1 || \N/A\}</span>',
 ' </div>',
 ' {selectedCustomerDetail.imei2 && (',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>IMEI 2:</span>',
 ' <span className=\font-mono font-bold text-sm text-emerald-400\>{selectedCustomerDetail.imei2}</span>',
 ' </div>',
 ' )}',
 ' </div>',
 ' </div>',
 '',
 ' {/* Grid 3: Referral / Reseller Details */}',
 ' <div className=\p-4 rounded-xl bg-blue-500/5 border border-blue-500/20 space-y-3\>',
 ' <h4 className=\text-xs font-semibold uppercase tracking-wider text-blue-400 flex items-center gap-1.5\>',
 ' <UserCheck className=\w-3.5 h-3.5\ /> Referral Details',
 ' </h4>',
 ' <div className=\grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs\>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Referred By:</span>',
 ' <span className=\font-bold text-sm text-blue-300\>',
 ' {selectedCustomerDetail.resellerName ? ${selectedCustomerDetail.resellerName} (Reseller) : \Direct Sale / Shop\}',
 ' </span>',
 ' </div>',
 ' {selectedCustomerDetail.resellerName && (',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Referral Commission:</span>',
 ' <span className=\font-medium text-foreground\>',
 ' {selectedCustomerDetail.referralCommissionPercent || 2}% ({formatCurrency(selectedCustomerDetail.referralCommissionAmount || 0)})',
 ' </span>',
 ' </div>',
 ' )}',
 ' </div>',
 ' </div>',
 '',
 ' {/* Grid 4: Complete Financial & Installment Breakdown */}',
 ' <div className=\p-4 rounded-xl bg-muted/40 border space-y-3\>',
 ' <h4 className=\text-xs font-semibold uppercase tracking-wider text-emerald-500 flex items-center gap-1.5\>',
 ' <DollarSign className=\w-3.5 h-3.5 text-emerald-500\ /> Financial & Installment Breakdown',
 ' </h4>',
 ' <div className=\grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs\>',
 ' <div className=\bg-background/60 p-2.5 rounded-lg border\>',
 ' <span className=\text-muted-foreground block text-[10px]\>Capital Invested:</span>',
 ' <span className=\font-bold text-blue-400\>{formatCurrency(selectedCustomerDetail.investmentUsed)}</span>',
 ' </div>',
 ' <div className=\bg-background/60 p-2.5 rounded-lg border\>',
 ' <span className=\text-muted-foreground block text-[10px]\>Total Selling Price:</span>',
 ' <span className=\font-bold text-foreground\>{formatCurrency(selectedCustomerDetail.sellingPrice)}</span>',
 ' </div>',
 ' <div className=\bg-background/60 p-2.5 rounded-lg border\>',
 ' <span className=\text-muted-foreground block text-[10px]\>Advance Payment:</span>',
 ' <span className=\font-bold text-emerald-400\>{formatCurrency(selectedCustomerDetail.advancePayment)}</span>',
 ' </div>',
 ' <div className=\bg-background/60 p-2.5 rounded-lg border\>',
 ' <span className=\text-muted-foreground block text-[10px]\>Monthly Installment:</span>',
 ' <span className=\font-bold text-purple-400\>{formatCurrency(selectedCustomerDetail.monthlyInstallment)}</span>',
 ' </div>',
 ' <div className=\bg-background/60 p-2.5 rounded-lg border\>',
 ' <span className=\text-muted-foreground block text-[10px]\>Total Paid So Far:</span>',
 ' <span className=\font-bold text-emerald-400\>{formatCurrency(selectedCustomerDetail.totalPaid)}</span>',
 ' </div>',
 ' <div className=\bg-background/60 p-2.5 rounded-lg border\>',
 ' <span className=\text-muted-foreground block text-[10px]\>Remaining Balance:</span>',
 ' <span className=\font-bold text-amber-400\>{formatCurrency(selectedCustomerDetail.remainingAmount)}</span>',
 ' </div>',
 ' </div>',
 '',
 ' <div className=\pt-2 border-t text-xs flex justify-between items-center\>',
 ' <span className=\text-muted-foreground\>Installment Plan:</span>',
 ' <span className=\font-semibold text-foreground\>',
 ' {selectedCustomerDetail.paidInstallments} of {selectedCustomerDetail.installmentMonths} Months Paid',
 ' </span>',
 ' </div>',
 ' </div>',
 '',
 ' {/* Grid 5: Important Dates */}',
 ' <div className=\p-4 rounded-xl bg-muted/20 border space-y-3\>',
 ' <h4 className=\text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-1.5\>',
 ' <Calendar className=\w-3.5 h-3.5\ /> Important Dates',
 ' </h4>',
 ' <div className=\grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs\>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Sale Date:</span>',
 ' <span className=\font-medium text-foreground\>{formatDate(selectedCustomerDetail.createdAt)}</span>',
 ' </div>',
 ' {selectedCustomerDetail.nextDueDate && (',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[11px]\>Next Installment Due Date:</span>',
 ' <span className=\font-medium text-amber-400\>{formatDate(selectedCustomerDetail.nextDueDate)}</span>',
 ' </div>',
 ' )}',
 ' </div>',
 ' </div>',
 '',
 ' {/* Grid 6: Defaulted Case Details (if applicable) */}',
 ' {selectedCustomerDetail.status === \defaulted\ && (',
 ' <div className=\p-4 rounded-xl bg-red-500/10 border border-red-500/20 space-y-2\>',
 ' <h4 className=\text-xs font-semibold uppercase tracking-wider text-red-500 flex items-center gap-1.5\>',
 ' <AlertTriangle className=\w-3.5 h-3.5\ /> Defaulted Case Details',
 ' </h4>',
 ' <p className=\text-xs text-muted-foreground\>',
 ' Reason: <strong className=\text-foreground\>{selectedCustomerDetail.lossReason || \Customer Defaulted\}</strong>',
 ' </p>',
 ' {selectedCustomerDetail.lossDate && (',
 ' <p className=\text-xs text-muted-foreground\>',
 ' Default Date: <strong className=\text-foreground\>{formatDate(selectedCustomerDetail.lossDate)}</strong>',
 ' </p>',
 ' )}',
 ' <div className=\grid grid-cols-2 gap-2 text-xs pt-2 border-t border-red-500/20\>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[10px]\>Total Case Loss:</span>',
 ' <span className=\font-bold text-red-500\>{formatCurrency(selectedCustomerDetail.remainingAmount)}</span>',
 ' </div>',
 ' <div>',
 ' <span className=\text-muted-foreground block text-[10px]\>Your 50% Loss Share:</span>',
 ' <span className=\font-bold text-purple-400\>{formatCurrency(Math.round(selectedCustomerDetail.remainingAmount * 0.5))}</span>',
 ' </div>',
 ' </div>',
 ' </div>',
 ' )}',
 ' </div>',
 '',
 ' <DialogFooter>',
 ' <Button variant=\outline\ onClick={() => setSelectedCustomerDetail(null)} className=\w-full\>',
 ' Close Customer Details',
 ' </Button>',
 ' </DialogFooter>',
 ' </>',
 ' )}',
 ' </DialogContent>',
 ' </Dialog>'
].join('\n');

const startMarker = '<div className=\space-y-2\>\n {customers.map';
const endMarker = '</div>\n )}\n </CardContent>';

const idx1 = code.indexOf(startMarker);
const idx2 = code.indexOf(endMarker, idx1);

if (idx1 !== -1 && idx2 !== -1) {
 code = code.substring(0, idx1) + cardsBlock + '\n' + code.substring(idx2);
}

if (!code.includes('selectedCustomerDetail &&')) {
 const lastDivIdx = code.lastIndexOf('</div>');
 if (lastDivIdx !== -1) {
 code = code.substring(0, lastDivIdx) + dialogBlock + '\n </div>\n );\n}\n';
 }
}

fs.writeFileSync(target, code, 'utf8');
console.log('Successfully updated investor portal page!');